name: industry_project
description: "A new Flutter project."
publish_to: "none"
publish_to: "none"
version: 0.1.0

environment:

  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  mailer: ^6.0.0
  sleek_circular_slider: ^2.0.1
  share_plus: ^9.0.0
  smooth_page_indicator: ^1.1.0
  syncfusion_flutter_charts: ^25.2.5
  rive: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/grafiek.png
    - assets/invullen.png
    - assets/begin.png
    - assets/starten.png
    - assets/images/main_button.png
    - assets/images/arrow_back.png
      #assets for rive
    - assets/flower.riv
